#!/usr/bin/python

import sys
# Takes a list of PDBs generated by Rosetta and assembles them into a single file suitable for analysis by Gromacs programs or dm.py
# To run enter "run ./pdb_assembler.py output_file_name.pdb input_file_names_without_appended_number_*"
# To pull from set of folders run as "run ./pdb_assembler.py output_file_name.pdb input_folder_name_*/input_file_names_*"
# Output number of written structures should match number in folder
#print "Syntax: outfile.pdb inputfiles*.pdb"

outf = open(sys.argv[1], 'w') # Output file name is the first argument
for (i, f) in enumerate(sys.argv[2:]): # Input files are all subsequent arguments
   outf.write("""REMARK    GENERATED BY pdb_assembler.py
TITLE     Protein in water t=   %.5f
REMARK    THIS IS A SIMULATION BOX
CRYST1   100.0   100.00    100.00  90.00  90.00  90.00 P 1           1
MODEL     %i
""" % (float(i)/1000, i))
   inf = open(f).readlines()
   for line in inf:
       outf.write(line)
   outf.write("""ENDMDL
""")

outf.close() 

print("Wrote %i structures to %s" % (len(sys.argv[2:]), sys.argv[1]))
